### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by re1**
Add Arch Linux dependencies to the readme, improve linting, add icons and fix a typo on the install script.

### CODE REVIEW

**Comment by omni6** [comment]
for people wo dont want to do everything step by step, here's the link to AUR [PKGBUILD](https://aur.archlinux.org/packages/sierrabreeze-kwin-decoration-git/), common solution to install on arch systems. should also included in README.md

**Comment by re1** [comment]
Added a link to the package and provided a yaourt command. Those who would like to install from the AUR manually will crawl for it anyway.

**Comment by trmdi** [comment]
The package for openSUSE Tumbleweed: https://software.opensuse.org//download.html?project=home%3Atrmdi&package=sierra-breeze

**Comment by re1** [comment]
Comments marked with 👍 have been fixed.

**Comment by re1** [comment]
@ishovkun Something you'd change?

**Pull request merged**
