### PR TITLE
Fix error build for Qt 5.15+ #66

### PR DESCRIPTION
**Pull request by KennFatt**

### CODE REVIEW

**Comment by KennFatt** [comment]
Edit:

ref: #66

**Comment by KieranMcCool** [comment]
Can confirm, complies fine on Qt 5.15 now.

**Comment by zmenciso** [comment]
Works for me, too!  Thanks!
```
Qt 5.15.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.1.0) on "xcb" 
OS: Arch Linux [linux version 5.7.5-arch1-1]
```

**Comment by abraaocrvlho** [comment]
I'm using version 5.15 and it still doesn't work

**Comment by OzoneHelix** [comment]
I can verify that this works correctly and does compile on qt 5.15 can we please merge this it fixes SierraBreeze

**Pull request merged**
