### PR TITLE
Set titlebar text color to terminal text color

### PR DESCRIPTION
**Pull request by alex47**
Before: 
Before

After: 
After

### CODE REVIEW

**Comment by trmdi** [comment]
**Found a bug:** the Application Menu icon isn't set to the right color.

image

**Comment by alex47** [comment]
@trmdi that bug is not related to the titlebar text color
I think you should rather open an issue for that

**Comment by ishovkun** [comment]
Sorry for being absent for so long. Github tells me that there are conflicts for this pull request. Please resolve them.

**Comment by alex47** [comment]
superseded by #32

**Pull request closed without merging**
